---
resource_types:
  # the npm-cache resource type
  - name: npm-cache
    type: docker-image
    source: { repository: ymedlop/npm-cache-resource, tag: latest }

resources:
  # a perfectly normal source repository with alot of dependencies
  - name: hapi
    type: git
    source:
      &repo-source # apply a YAML anchor so we can refer to this in the cache resource
      uri: https://github.com/joeyrbrown/hello_hapi.git
      branch: master

  # a resource caching the dependencies listed in the source repository
  - name: npm-repo-cache
    type: npm-cache # as defined above
    source:
      <<: *repo-source # the source is the same as the corresponding git resource ...
      paths: # ... except that it's only interested in files listing dependencies
        - package.json

jobs:
  - name: cache
    plan:
      - get: hapi
        trigger: true

      - get: npm-repo-cache

  - name: Tests
    plan:
      - get: repo
        trigger: true
        passed: [cache]

      - get: npm-repo-cache
        passed: [cache]

      - task: Test Suite
        file: hapi/ci/tasks/run_tests.yml
